

CREATE TABLE INVOICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    QUANTITY INT NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL
);